### ISSUE TITLE
grammar nazi

### ISSUE THREAD

**Issue by Mesysz** [shyBBy/bookingVisitApp#13]
<img width="774" alt="Screenshot 2022-07-11 at 17 44 33" src="https://user-images.githubusercontent.com/6567683/178303569-2f94f8a1-b3a0-414f-8f6b-ae3dcab114df.png">
should be Total visits and active visits i think

**Comment by shyBBy** [comment]
![image](https://user-images.githubusercontent.com/34265689/178310649-8df762ba-4216-4ded-8393-6026250e993d.png)
